### ISSUE TITLE
feature: return to normal mode after coerce done in visual mode

### ISSUE THREAD

**Issue by zhengpd** [gregorias/coerce.nvim#11]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

I would like to return to normal mode automatically after text coerced in visual mode. No option to achieve this yet.

### Describe the solution you'd like

May be an option like `back_to_normal = true`.

### Describe alternatives you've considered

Or option `stay_visual = false`.

**Comment by gregorias** [comment]
Makes sense that this should be the default, because default commands work like that (I just tested it on `d`elete). Thanks for letting me know. I’ll take a look.
