### ISSUE TITLE
feature: visual mode support

### ISSUE THREAD

**Issue by svermeulen** [gregorias/coerce.nvim#2]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

Applying coerce to specific ranges of text rather than current word under cursor

### Describe the solution you'd like

Would be great if you could enter visual mode, select some text, then trigger coerce

### Describe alternatives you've considered

Using coerce on current word works but fails with special characters.  For example, doing `crd` to convert to dot case, then `crs` to convert back fails since dot character ends the word

**Comment by gregorias** [comment]
Thanks for filing this. It’s on my roadmap, and I should get this done soon.
