### ISSUE TITLE
`vim.lsp.buf.rename` returns `nil` on successful rename

### ISSUE THREAD

**Issue by tdcdev** [gregorias/coerce.nvim#5]
Hi @gregorias,

Thanks for this nice plugin!

I have an issue with the LSP rename function. I am using nvim 0.10 and pyright LSP server.

When I try to force a word it seems that the LSP rename is not called and only the local transformer is triggered. After some digging, it appears that the LSP rename is called but is overridden by the local transformer.

I think the problem comes from [here](https://github.com/gregorias/coerce.nvim/blob/fdbc61acc81da3c7179e27d4122d5d794aeae2e5/lua/coerce/transformer.lua#L56) as the `vim.lsp.buf.rename` returns nothing if the rename is done without errors.

Regards,

**Comment by gregorias** [comment]
Hi Thomas,

Thanks for reporting.

The default lsp rename is [`transform_lsp_rename_with_failover`](https://github.com/gregorias/coerce.nvim/blob/fdbc61acc81da3c7179e27d4122d5d794aeae2e5/lua/coerce/transformer.lua#L75). It’s intended behavior that if the rename fails, we just apply a local transformation. It would only be a bug if LSP rename was working, but Coerce somehow didn’t recognize or use that.

If you’d like to have different behavior:

1. You can relatively easily configure your own _modes_ ([instructions](https://github.com/gregorias/coerce.nvim?tab=readme-ov-file#register-a-new-mode), [default modes](https://github.com/gregorias/coerce.nvim/blob/fdbc61acc81da3c7179e27d4122d5d794aeae2e5/lua/coerce.lua#L20-L45)).
2. You can make a case that this plugin should use different defaults.

**Comment by tdcdev** [comment]
> It would only be a bug if LSP rename was working, but Coerce somehow didn’t recognize or use that.

I think this is exactly what happens. Because [transform_lsp_rename](https://github.com/gregorias/coerce.nvim/blob/fdbc61acc81da3c7179e27d4122d5d794aeae2e5/lua/coerce/transformer.lua#L51) returns the result of `vim.lsp.buf.rename` which is nil if the rename succeed.

EDIT:

Actually it seems [vim.lsp.buf.rename](https://github.com/neovim/neovim/blob/88cd7a6cddf8f512b305c2f3f479747d7a9a9de7/runtime/lua/vim/lsp/buf.lua#L298) returns nothing.

**Comment by gregorias** [comment]
I'm busy at the moment, so I'll speculate and double check later.
Especially the rename not returning anything. That's weird.

Anyway, I believe there's a unit test for LSP rename. If what you are
saying is correct, then LSP rename would never work. You could consider
double checking on your side of LSP rename works on your end, but doesn't
work with Coerce.
