### ISSUE TITLE
feature request: dot repeatable

### ISSUE THREAD

**Issue by kevintraver** [gregorias/coerce.nvim#6]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

Current commands are not dot repeatable

### Describe the solution you'd like

Current commands to be dot repeatable

### Describe alternatives you've considered

n/a

**Comment by gregorias** [comment]
Thanks, will work on fixing this as soon as I get the time.

**Comment by gregorias** [comment]
Note to self: I found out why dot-repeatability is not present. In https://github.com/gregorias/coerce.nvim/blob/e537af2f2828952a950962c1067020d922c6405a/lua/coerce/operator.lua#L45-L48, I wrote a nice helper function that turns operator mechanics into a coroutine, which lets me use a more readable sequential style. The unfortunate side-effect is that the operatorfunc callback only contains some coroutine utility function. I’ll probably will need to rewrite the code to contain the entire coercion code in that callback.
