### ISSUE TITLE
feature: allow custom keymap prefix

### ISSUE THREAD

**Issue by zhengpd** [gregorias/coerce.nvim#7]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

`gc` is the keymap for builtin commenting feature, which conflicts with `gcr` in visual mode from `coerce.nvim`.

ref: https://github.com/neovim/neovim/pull/28176

### Describe the solution you'd like

Allow custom keymap prefix with simple option like `prefix = "ga"`.

### Describe alternatives you've considered

None.

**Comment by gregorias** [comment]
Sounds good.
