### ISSUE TITLE
bug: Docs have v3.0.0 listed but no tag exists

### ISSUE THREAD

**Issue by dr-kernel** [gregorias/coerce.nvim#8]
### Did you check docs and existing issues?

- [X] I have read the plugin’s docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

10.1

### Operating system & version

Linux

### Describe the bug

Please update tags to match docs, or revert docs until tag exists.  

### Steps to reproduce

1. Try to use doc tag
2. Fail to install using Lazy due to missing tag

### Expected Behavior

Doc to match available repo tags.

**Comment by gregorias** [comment]
Thanks.
